repos:
  - repo: local
    hooks:
      - id: update-requirements
        name: Update requirements.txt
        entry: bash -c 'pip freeze > requirements.txt'
        language: system
        files: ^Pipfile$
